baseURL: http://designcommun.fr/cahiers/les-numeriques-situes
languageCode: fr
title: Les numériques situés
theme: cahiers-design-commun
author:
  name: Gauthier Roussilhe
  homepage: http://gauthierroussilhe.com/fr
