baseURL: http://designcommun.fr/cahiers/les-numeriques-situes
languageCode: fr
languageName: Français
defaultContentLanguage: fr
title: Les numériques situés
theme: cahiers-design-commun
author:
  name: Gauthier Roussilhe
  homepage: http://gauthierroussilhe.com/fr
markup:
  goldmark:
    renderer:
      unsafe: true
module:
  imports:
    - path: github.com/jygastaud/hugo-microtypo/microtypo
      disable: false
